"""Added field superuser in UsersReport

Revision ID: fc91cb379eea
Revises: f601d29e39c5
Create Date: 2018-06-09 11:25:04.437810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc91cb379eea'
down_revision = 'f601d29e39c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавил server_default
    op.add_column(
        'users',
        sa.Column(
            'superuser', sa.Boolean(), nullable=False, server_default='f'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'superuser')
    # ### end Alembic commands ###
